package ro.btanase.chordlearning.mybatisgen.model;

public class Settings {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SETTINGS.S_ID
     *
     * @mbggenerated Fri Apr 06 14:07:40 EEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SETTINGS.S_KEY
     *
     * @mbggenerated Fri Apr 06 14:07:40 EEST 2012
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SETTINGS.S_VALUE
     *
     * @mbggenerated Fri Apr 06 14:07:40 EEST 2012
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SETTINGS.S_ID
     *
     * @return the value of PUBLIC.SETTINGS.S_ID
     *
     * @mbggenerated Fri Apr 06 14:07:40 EEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SETTINGS.S_ID
     *
     * @param id the value for PUBLIC.SETTINGS.S_ID
     *
     * @mbggenerated Fri Apr 06 14:07:40 EEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SETTINGS.S_KEY
     *
     * @return the value of PUBLIC.SETTINGS.S_KEY
     *
     * @mbggenerated Fri Apr 06 14:07:40 EEST 2012
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SETTINGS.S_KEY
     *
     * @param key the value for PUBLIC.SETTINGS.S_KEY
     *
     * @mbggenerated Fri Apr 06 14:07:40 EEST 2012
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SETTINGS.S_VALUE
     *
     * @return the value of PUBLIC.SETTINGS.S_VALUE
     *
     * @mbggenerated Fri Apr 06 14:07:40 EEST 2012
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SETTINGS.S_VALUE
     *
     * @param value the value for PUBLIC.SETTINGS.S_VALUE
     *
     * @mbggenerated Fri Apr 06 14:07:40 EEST 2012
     */
    public void setValue(String value) {
        this.value = value;
    }
}